language: c

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created via the "travis encrypt" command using the project repo's public key
    - secure: "pSpxU3KeoSNcRfXp33Xvw5WjFLEvKqnHOovpk5YR430rmJEI43CmD8/ogovbw/iTvBQNWUTdb3qLWDzOpnu9IibxsUkJX56Wjme6wyPcVYSjfy35Y0AMC+fScmIVdCRcLE6oJSryOLhOPkpoEBk+eVKQWjsBXP038TDoARanW1xAaakwginWPXjBgAPRkJ4Re202+kP6Er0htKyhDk6xfGKsD8uCQ2PvbDcueSFVc6T0cVbj1Z1bbl5BjutywqwuAwc+bLc8jV62TjYDtSehZK98qZUbBiZ2bG3wMcJF/URy/C1/D7hZ8FewigaGsaWL35JfxPRXaUnXnRrnXG6ogubENbS9Xf0rb8Sf4cU2oPwYxrTzuzLiSbEKNiBylDsXd6kgn+QEkEN8s7saTRpqz2fP+21RQHqlCLeLalTWHr8uKHTnPvmCEVLhL5sJDuHJoMX4KPAc+J7mRq8XGBkgQSSC874TecWUxi4w3u5Cb+guurFuuuXe/TFOZDAcp3eGnGMJxxNdkPAWNXZzbz5VNCDXkv9CrLZq+RZn9RCkk3Wene4SKj+WpkLCduzIKTEjM0AeyFKJ+XK4WJjwmP3wSH22oelM1jeXoFPDtLld4zYlGMN1BUsHW/Y6oPe2YGkN+pmOQo6OsSF3+EHxnMuKVm9LV2/fjJtMzXzVXkZpA8c="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:

  - echo travis_fold:start:AUTORECONF
  - autoreconf --install
  - echo travis_fold:end:AUTORECONF

  - echo travis_fold:start:CONFIGURE
  - ./configure
  - echo travis_fold:end:CONFIGURE

  - echo travis_fold:start:MAKE
  - make
  - echo travis_fold:end:MAKE

  - echo travis_fold:start:COVERAGE
  - make coverage
  - echo travis_fold:end:COVERAGE

after_success:

  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "LeakyAbstractions/fmt"
      description: "A tiny C string formatting library"
    notification_email: coverity@guillermo.dev
    build_command_prepend: "autoreconf --install; ./configure; make clean"
    build_command: "make -j 4"
    branch_pattern: coverity_scan
